import React from 'react';
    import Link from 'next/link';
    import '../styles/globals.css';

    export const metadata = {
        title: 'geollm',
        description: 'Generated by Next.js',
    }

    export default function RootLayout({ children }) {
        return (
            <html lang="en">
                <body>
                    <header>
                        <nav className="p-4 bg-gray-100">
                            <ul className="flex space-x-4">
                                <li><Link href="/">Home</Link></li>
                            </ul>
                        </nav>
                    </header>
                    <main>{children}</main>
                </body>
            </html>
        )
    }