"""adding session id to polygon

Revision ID: 9abc95bda6e6
Revises: 6a6b4a64f30b
Create Date: 2024-12-16 17:36:35.416440

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision: str = '9abc95bda6e6'
down_revision: Union[str, None] = '6a6b4a64f30b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('analysis_polygons', sa.Column('session_id', sa.String(), nullable=True))
    op.create_index(op.f('ix_analysis_polygons_session_id'), 'analysis_polygons', ['session_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_analysis_polygons_session_id'), table_name='analysis_polygons')
    op.drop_column('analysis_polygons', 'session_id')
    # ### end Alembic commands ###
