"""initial migration

Revision ID: be788c5041eb
Revises: 
Create Date: 2024-12-16 13:08:55.696832

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision: str = 'be788c5041eb'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('analysis_polygons',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('geometry', geoalchemy2.types.Geometry(geometry_type='POLYGON', srid=4326, spatial_index=False, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sentinel_data', sa.JSON(), nullable=True),
    sa.Column('cropland_data', sa.JSON(), nullable=True),
    sa.Column('vision_results', sa.JSON(), nullable=True),
    sa.Column('carbon_estimates', sa.JSON(), nullable=True),
    sa.Column('analysis_metadata', sa.JSON(), nullable=True),
    sa.Column('analysis_history', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_analysis_polygons_id'), 'analysis_polygons', ['id'], unique=False)
    op.create_table('demo_table',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('demo_field', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_demo_table_id'), 'demo_table', ['id'], unique=False)
    op.create_table('exports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('polygon_id', sa.Integer(), nullable=True),
    sa.Column('format', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('file_path', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['polygon_id'], ['analysis_polygons.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('vision_analyses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('polygon_id', sa.Integer(), nullable=True),
    sa.Column('model_version', sa.String(), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('results', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['polygon_id'], ['analysis_polygons.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vision_analyses')
    op.drop_table('exports')
    op.drop_index(op.f('ix_demo_table_id'), table_name='demo_table')
    op.drop_table('demo_table')
    op.drop_index(op.f('ix_analysis_polygons_id'), table_name='analysis_polygons')
    op.drop_table('analysis_polygons')
    # ### end Alembic commands ###
