"""dropping demo tables

Revision ID: d9d22e23096f
Revises: 9abc95bda6e6
Create Date: 2024-12-17 08:39:21.991385

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision: str = 'd9d22e23096f'
down_revision: Union[str, None] = '9abc95bda6e6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_demo_table_id', table_name='demo_table')
    op.drop_table('demo_table')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('demo_table',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('demo_field', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='demo_table_pkey')
    )
    op.create_index('ix_demo_table_id', 'demo_table', ['id'], unique=False)
    # ### end Alembic commands ###
